'use strict';

const AGENT_META = Object.freeze({
  claude: { id: 'claude', label: 'Claude', icon: 'claude-icon.svg' },
  codex: { id: 'codex', label: 'Codex', icon: 'codex-icon.svg' },
  antigravity: { id: 'antigravity', label: 'Antigravity', icon: 'antigravity-icon.png' },
  opencode: { id: 'opencode', label: 'opencode', icon: 'opencode-icon.svg' },
  kimi: { id: 'kimi', label: 'Kimi Code', icon: 'kimi-icon.png' },
  grok: { id: 'grok', label: 'Grok Build', icon: 'grok-icon.svg' },
  cursor: { id: 'cursor', label: 'Cursor Agent', icon: 'cursor-icon.svg' },
});

const AGENT_ORDER = Object.freeze(Object.keys(AGENT_META));
const DEFAULT_PROMPT_CHAR_LIMIT = 18000;
const DEFAULT_RECENT_CHAR_BUDGET = 9000;
const DEFAULT_EXCERPT_CHARS = 1600;
const MAX_TERMINAL_ACTIVITY_ENTRIES = 8;

const SKIPPED_MESSAGE_MARKERS = [
  'This session is being continued from a previous conversation that ran out of context',
  'Caveat: The messages below were generated by the user while running local commands',
];

function getAgentMeta(agentType) {
  return AGENT_META[agentType] || AGENT_META.claude;
}

function messageText(content) {
  if (typeof content === 'string') return content;
  if (content == null) return '';
  if (Array.isArray(content)) {
    return content.map((item) => {
      if (typeof item === 'string') return item;
      if (item && typeof item.text === 'string') return item.text;
      if (item && typeof item.content === 'string') return item.content;
      return '';
    }).filter(Boolean).join('\n');
  }
  if (typeof content.text === 'string') return content.text;
  try {
    return JSON.stringify(content);
  } catch (_) {
    return String(content);
  }
}

function normalizeMessages(messages) {
  if (!Array.isArray(messages)) return [];
  return messages.map((message) => {
    const rawRole = message && message.role;
    const role = rawRole === 'assistant' || rawRole === 'user' ? rawRole : 'tool';
    const content = messageText(message && message.content).trim();
    return {
      role,
      content,
      timestamp: message && message.timestamp ? message.timestamp : null,
    };
  }).filter((message) => (
    message.content &&
    !SKIPPED_MESSAGE_MARKERS.some((marker) => message.content.includes(marker))
  ));
}

function clip(text, maxChars = DEFAULT_EXCERPT_CHARS) {
  const clean = String(text || '').trim();
  if (clean.length <= maxChars) return clean;
  return `${clean.slice(0, Math.max(0, maxChars - 1)).trimEnd()}…`;
}

function clipInline(text, maxChars) {
  return clip(text, maxChars).replace(/\s+/g, ' ');
}

function normalizeTerminalMeta(terminalMeta, fallbackTitle = '') {
  const meta = terminalMeta && typeof terminalMeta === 'object' && !Array.isArray(terminalMeta)
    ? terminalMeta
    : {};
  const activityHistory = Array.isArray(meta.activityHistory)
    ? meta.activityHistory
      .slice(0, MAX_TERMINAL_ACTIVITY_ENTRIES)
      .map((entry) => {
        if (!entry || typeof entry !== 'object') return null;
        const activity = clipInline(entry.activity, 320);
        if (!activity) return null;
        const normalized = { activity };
        if (entry.created_at) normalized.created_at = clipInline(entry.created_at, 80);
        if (entry.status_key) normalized.status_key = clipInline(entry.status_key, 80);
        return normalized;
      })
      .filter(Boolean)
    : [];

  return {
    title: clipInline(meta.title || fallbackTitle, 300),
    goal: clipInline(meta.goal, 1200),
    workStatus: clipInline(meta.workStatus, 100) || null,
    activityHistory,
  };
}

function renderTerminalContinuity(terminalMeta) {
  const lines = [
    '## Agent continuity',
    `- Agent title: ${terminalMeta.title || 'Untitled conversation'}`,
    `- Goal: ${terminalMeta.goal || 'Not set'}`,
    `- Work status: ${terminalMeta.workStatus || 'Not set'}`,
  ];
  if (terminalMeta.activityHistory.length) {
    lines.push('- Recent agent activity:');
    terminalMeta.activityHistory.forEach((entry) => {
      lines.push(`  - ${entry.activity}`);
    });
  } else {
    lines.push('- Recent agent activity: None recorded');
  }
  return lines.join('\n');
}

function messageBlock(message, maxChars = DEFAULT_EXCERPT_CHARS) {
  const speaker = message.role === 'assistant'
    ? 'Source agent'
    : (message.role === 'user' ? 'User' : 'Tool / system context');
  return `### ${speaker}\n${clip(message.content, maxChars)}`;
}

function findLast(messages, role) {
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    if (messages[index].role === role) return messages[index];
  }
  return null;
}

function findFirst(messages, role) {
  return messages.find((message) => message.role === role) || null;
}

function selectCheckpoints(messages, maxCount = 4) {
  if (messages.length <= 4) return [];
  const firstIndex = 1;
  const lastIndex = messages.length - 2;
  const indexes = new Set();

  for (let step = 1; step <= maxCount; step += 1) {
    const ratio = step / (maxCount + 1);
    indexes.add(Math.round(firstIndex + ((lastIndex - firstIndex) * ratio)));
  }

  return Array.from(indexes)
    .sort((a, b) => a - b)
    .map((index) => messages[index])
    .filter(Boolean);
}

function buildStructuredSummary(messages) {
  const sections = [];
  const firstUser = findFirst(messages, 'user');
  const lastUser = findLast(messages, 'user');
  const lastAssistant = findLast(messages, 'assistant');

  if (firstUser) sections.push(`### Original request\n${clip(firstUser.content)}`);
  if (lastUser && lastUser !== firstUser) {
    sections.push(`### Latest user direction\n${clip(lastUser.content)}`);
  }
  if (lastAssistant) {
    sections.push(`### Latest source-agent update\n${clip(lastAssistant.content)}`);
  }

  const checkpoints = selectCheckpoints(messages);
  if (checkpoints.length) {
    sections.push(
      `### Conversation checkpoints\n${checkpoints.map((message, index) => (
        `${index + 1}. **${message.role === 'assistant' ? 'Source agent' : 'User'}:** ${clip(message.content, 700).replace(/\n+/g, ' ')}`
      )).join('\n')}`
    );
  }

  return sections.join('\n\n');
}

function buildRecentTranscript(messages, charBudget = DEFAULT_RECENT_CHAR_BUDGET) {
  const selected = [];
  let used = 0;

  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const block = messageBlock(messages[index], 2600);
    const cost = block.length + 2;
    if (selected.length && used + cost > charBudget) break;
    selected.unshift(block);
    used += cost;
  }

  return {
    text: selected.join('\n\n'),
    includedMessages: selected.length,
  };
}

function renderTranscriptMarkdown({
  messages,
  title,
  sourceAgent,
  workingDirectory,
  sourceWorkingDirectory = '',
  terminalMeta,
}) {
  const source = getAgentMeta(sourceAgent);
  const continuity = normalizeTerminalMeta(terminalMeta, title);
  const originalWorkingDirectory = sourceWorkingDirectory || workingDirectory;
  const directoryLines = originalWorkingDirectory && originalWorkingDirectory !== workingDirectory
    ? [
      `- Source working directory: ${originalWorkingDirectory}`,
      `- Working directory: ${workingDirectory || 'Unknown'}`,
    ]
    : [`- Working directory: ${workingDirectory || 'Unknown'}`];
  const lines = [
    `# ${continuity.title || title || 'Conversation handoff transcript'}`,
    '',
    `- Source model: ${source.label}`,
    ...directoryLines,
    `- Messages: ${messages.length}`,
    '',
    renderTerminalContinuity(continuity),
    '',
    '---',
    '',
  ];

  messages.forEach((message) => {
    lines.push(messageBlock(message, 200000), '');
  });

  return lines.join('\n');
}

function buildConversationHandoff({
  messages,
  title,
  sourceAgent = 'claude',
  targetAgent = 'codex',
  sourceSessionId = '',
  workingDirectory = '',
  sourceWorkingDirectory = '',
  sandboxPromotion = false,
  transcriptPath = '',
  maxPromptChars = DEFAULT_PROMPT_CHAR_LIMIT,
  terminalMeta = {},
}) {
  const normalized = normalizeMessages(messages);
  const source = getAgentMeta(sourceAgent);
  const target = getAgentMeta(targetAgent);
  const originalWorkingDirectory = sourceWorkingDirectory || workingDirectory;
  const directoryLines = originalWorkingDirectory && originalWorkingDirectory !== workingDirectory
    ? [
      `- Source working directory: ${originalWorkingDirectory}`,
      `- Working directory: ${workingDirectory || 'Unknown'}`,
    ]
    : [`- Working directory: ${workingDirectory || 'Unknown'}`];
  const continuity = normalizeTerminalMeta(terminalMeta, title);
  const conversationTitle = continuity.title || title || 'Untitled conversation';
  const summary = buildStructuredSummary(normalized);
  const recent = buildRecentTranscript(normalized);
  const transcriptReference = transcriptPath
    ? `The complete, read-only transcript is available at:\n${transcriptPath}`
    : 'The complete source transcript remains unchanged in the source model history.';

  const header = [
    sandboxPromotion
      ? '# Continue a Sandbox conversation in a real project'
      : '# Continue a conversation from another LLM',
    '',
    sandboxPromotion
      ? `Continue this Sandbox work in a new ${target.label} conversation inside the real project.`
      : `You are ${target.label}. This work started in ${source.label}; continue it as the next collaborator.`,
    'Do not restart the task or repeat completed work. Inspect the current files, git state, and task state before changing anything; disk and repository state are authoritative when they differ from this handoff.',
    '',
    '## Handoff metadata',
    `- Source model: ${source.label}`,
    `- Source session: ${sourceSessionId || 'Unknown'}`,
    `- Conversation: ${conversationTitle}`,
    ...directoryLines,
    `- Source messages: ${normalized.length}`,
    '',
    renderTerminalContinuity(continuity),
    '',
    '## Focused conversation summary',
    summary || 'No readable user/assistant messages were found.',
    '',
    '## Most recent messages (verbatim excerpts)',
    recent.text || 'No recent messages available.',
    '',
    '## Full transcript',
    transcriptReference,
    '',
    'Continue from the latest user direction. Briefly acknowledge the handoff, verify the current state, and then proceed with the unfinished work.',
  ].join('\n');

  const safeLimit = Math.max(4000, Number(maxPromptChars) || DEFAULT_PROMPT_CHAR_LIMIT);
  let prompt = header;
  let truncated = false;
  if (prompt.length > safeLimit) {
    truncated = true;
    const suffix = [
      '',
      '## Full transcript',
      transcriptReference,
      '',
      'Continue from the latest user direction. Verify the current state, then proceed with the unfinished work.',
    ].join('\n');
    prompt = `${prompt.slice(0, Math.max(0, safeLimit - suffix.length - 2)).trimEnd()}\n\n${suffix}`;
  }

  return {
    prompt,
    summary,
    terminalMeta: continuity,
    normalizedMessages: normalized,
    stats: {
      sourceMessages: normalized.length,
      recentMessages: recent.includedMessages,
      promptChars: prompt.length,
      estimatedPromptTokens: Math.ceil(prompt.length / 4),
      truncated,
    },
  };
}

module.exports = {
  AGENT_META,
  AGENT_ORDER,
  DEFAULT_PROMPT_CHAR_LIMIT,
  buildConversationHandoff,
  buildStructuredSummary,
  getAgentMeta,
  normalizeTerminalMeta,
  normalizeMessages,
  renderTranscriptMarkdown,
};
